
# config file version
apiVersion: 1

# Provisioning Grafana
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: Prometheus AlertManager
    type: camptocamp-prometheus-alertmanager-datasource
    access: proxy
    url: http://alertmanager:9093


